blank_issues_enabled: true
contact_links:
  - name: Security Vulnerability
    url: https://github.com/JyriWee/ergometer-app/security/advisories/new
    about: Report sensitive vulnerabilities privately.
